// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASsV7TS9UpF5wM9EPXgpECJo1sXSxel8k',
    appId: '1:205299956537:web:e11301159f141ae73146e8',
    messagingSenderId: '205299956537',
    projectId: 'ecommerce-81956',
    authDomain: 'ecommerce-81956.firebaseapp.com',
    storageBucket: 'ecommerce-81956.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENfD7fA261-3cp92MSOL0uDDFa6bkBeE',
    appId: '1:205299956537:android:e94aa2bd825feedd3146e8',
    messagingSenderId: '205299956537',
    projectId: 'ecommerce-81956',
    storageBucket: 'ecommerce-81956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDttelzeDruuAYpwJb2L7GLPDFdvuLp2kA',
    appId: '1:205299956537:ios:006700ae403a73e43146e8',
    messagingSenderId: '205299956537',
    projectId: 'ecommerce-81956',
    storageBucket: 'ecommerce-81956.appspot.com',
    iosBundleId: 'com.example.sampleEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDttelzeDruuAYpwJb2L7GLPDFdvuLp2kA',
    appId: '1:205299956537:ios:006700ae403a73e43146e8',
    messagingSenderId: '205299956537',
    projectId: 'ecommerce-81956',
    storageBucket: 'ecommerce-81956.appspot.com',
    iosBundleId: 'com.example.sampleEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASsV7TS9UpF5wM9EPXgpECJo1sXSxel8k',
    appId: '1:205299956537:web:7f5fef699a4fabd73146e8',
    messagingSenderId: '205299956537',
    projectId: 'ecommerce-81956',
    authDomain: 'ecommerce-81956.firebaseapp.com',
    storageBucket: 'ecommerce-81956.appspot.com',
  );
}
